nscaledev/uni-ui

charts/ui/templates/deployment.yaml, charts/ui/values.yaml
These have been pushed down into the server now, so they can be tied to the region configuration.
=> Remove Legacy Flags

src/lib/client.ts, src/lib/credentials.js, src/lib/shell/ShellAppBar.svelte, src/routes/+layout.svelte, src/routes/oauth2/callback/+page.svelte
We can cache the id_token until we are told to fully log out.  Now when an authorization_token expires, and is unset, we can trigger the OIDC authorization flow with the extsing email hint and, pow, automatic relog, in lieu of supporting reflresh_token.
=> Add OIDC login_hint

src/lib/credentials/index.ts, src/lib/login/index.ts, src/lib/shell/ShellAppBar.svelte, src/lib/shell/ShellSideBar.svelte, src/routes/(shell)/identity/tokens/+page.svelte, src/routes/(static)/oauth2/callback/+page.svelte
Okay so on reflection having an API for PATs is just wrong as you'd eventually have to share a refresh token, which being single use would log you out as soon as tooling refreshed, or vice versa, or the token was revoked.  So it's common sense that you do the oauth2 flow again in order to start a new ancestry of tokens.  Luckily we can just reuse what's already there and use the client state to control how the resulting token is handled.
=> Add PAT Provisioning

charts/ui/Chart.yaml, src/lib/formatters/index.ts, src/lib/layouts/ShellListItem.svelte, src/lib/layouts/ShellPage.svelte, src/lib/layouts/ShellViewHeader.svelte, src/routes/(shell)/identity/groups/view/[id]/+page.svelte, src/routes/(shell)/identity/organizations/view/[id]/+page.svelte, src/routes/(shell)/identity/projects/view/[id]/+page.svelte
This lets us do fun things like rendering metadata on the view, and binding to it in a nice generica way and we instantly can update names and descriptions.
=> Make all Resource Views use Shared Header

src/lib/layouts/ShellMetadataSection.svelte, src/lib/layouts/ShellViewHeader.svelte, src/lib/validation/index.ts, src/routes/(shell)/identity/groups/create/+page.svelte, src/routes/(shell)/identity/groups/view/[id]/+page.svelte, src/routes/(shell)/identity/oauth2providers/+page.svelte, src/routes/(shell)/identity/oauth2providers/create/+page.svelte, src/routes/(shell)/identity/organizations/view/[id]/+page.svelte, src/routes/(shell)/identity/projects/create/+page.svelte, src/routes/(shell)/identity/projects/view/[id]/+page.svelte, src/routes/(shell)/infrastructure/clusters/create/+page.svelte
Make all create/updated views use the same metadata component that pacakges up all the validation into a single source of truth.  Plumb that into the rest of the code base.
=> Unify Metadata Handling

charts/ui/Chart.yaml, src/lib/WorkloadPoolCreate.svelte, src/routes/(shell)/infrastructure/clusters/create/+page.svelte
Like the prior change, it makes code more compatible with creation and updates, and actually cleaner.
=> Make Workload Pool View Driven By Model

charts/ui/Chart.yaml, src/routes/(shell)/infrastructure/clusters/+page.svelte, src/routes/(shell)/infrastructure/clusters/create/+page.svelte, src/routes/(shell)/infrastructure/clusters/view/[id]/+page.svelte
Now about to become really important for testing... And just to prove to myself what I've done in the past couple changes is the right course of action, pulling this off was mostly trivial after the initial copy from the create view.
=> Add Back Cluster Updates

charts/ui/Chart.yaml, src/lib/StatusIcon.svelte, src/lib/layouts/Badge.svelte, src/lib/layouts/ShellListItem.svelte, src/lib/layouts/ShellMetadataItem.svelte, src/lib/layouts/ShellViewHeader.svelte, src/lib/openapi/region/.openapi-generator/FILES, src/lib/openapi/region/apis/DefaultApi.ts, src/lib/openapi/region/models/IdentityRead.ts, src/lib/openapi/region/models/IdentitySpec.ts, src/lib/openapi/region/models/IdentityWriteSpec.ts, src/lib/openapi/region/models/index.ts, src/lib/regionutil/index.ts, src/routes/(shell)/infrastructure/clusters/+page.svelte, src/routes/(shell)/infrastructure/clusters/create/+page.svelte, src/routes/(shell)/infrastructure/clusters/view/[id]/+page.svelte, src/routes/(shell)/regions/identities/+page.svelte
On reflection mapping region IDs to project scoped region names was way too complex, so we've moved to organization scoped regions.  We can still - under the hood - do any project filtering, but crucially only perform a single lookup for all identities/clusters.  As these two primitives have parity now, we can handle regions generically and add in a new item badge to convey which region something is living in.
=> Add Region Display

charts/ui/Chart.yaml, src/lib/clients/index.ts
When a refresh token is used, we need to update the access token in session storage to account for the updated expiry time etc.  There is still a race whereby multiple API calls at once will do multiple refresh promises which we could sort out at some point.
=> Fix Refresh Token Handling

charts/ui/Chart.yaml, src/lib/layouts/ShellListItem.svelte
There is a race where the project ID should be resolved before the project list is available, thus displaying the ID and not the name.  By making this more reactive we will update when the data is available.
=> Fix Project Scope Resolution

charts/ui/Chart.yaml, package-lock.json, src/lib/shell/ShellSideBar.svelte, src/routes/(shell)/identity/oauth2providers/+page.svelte, src/routes/(shell)/identity/projects/+page.svelte, src/routes/(shell)/infrastructure/clustermanagers/+page.svelte, src/routes/(shell)/infrastructure/clusters/+page.svelte, src/routes/(shell)/regions/identities/+page.svelte
Hopefully fix an annoying situation where a token refresh caused tickers to call onDestroy erroneously and break things.  Remove the last warnings from the linter.  Remove as many CVEs as we can.
=> Sprinkling of Fixes

charts/ui/Chart.yaml, src/routes/(shell)/regions/identities/+page.svelte, src/routes/(shell)/regions/physicalnetworks/+page.svelte
Makes this properly reactive rather than being a slave to tickers, basically copies the logic from the identity service views.
=> Fix Regions View Updates

src/lib/forms/Clipboard.svelte, src/routes/(shell)/identity/oauth2providers/create/+page.svelte, src/routes/(shell)/identity/serviceaccounts/create/+page.svelte, src/routes/(shell)/identity/serviceaccounts/view/[id]/+page.svelte
Removed in skeleton 3, plus there is a native API to use in the browser now.
=> Remove Clipboard

charts/ui/Chart.yaml, src/routes/(shell)/identity/groups/create/+page.svelte, src/routes/(shell)/identity/groups/view/[id]/+page.svelte, src/routes/(shell)/identity/oauth2providers/create/+page.svelte, src/routes/(shell)/identity/projects/create/+page.svelte, src/routes/(shell)/identity/projects/view/[id]/+page.svelte, src/routes/(shell)/identity/serviceaccounts/create/+page.svelte, src/routes/(shell)/identity/serviceaccounts/view/[id]/+page.svelte, src/routes/(shell)/identity/users/create/+page.svelte, src/routes/(shell)/identity/users/view/[id]/+page.svelte
An explicit cancel button is simpler on the mind than having to navigate back to the main view with the nav, which is harder on mobile as it's hidden in a drawer.
=> Improve Create View Dialog Flows

src/lib/forms/PopupButton.svelte, src/lib/layouts/GroupedList.svelte, src/lib/layouts/ShellListItem.svelte, src/lib/regionutil/index.ts, src/lib/shell/AppBar.svelte, src/routes/dashboard/compute/clusters/+page.svelte, src/routes/dashboard/compute/clusters/create/+page.svelte, src/routes/dashboard/kubernetes/clusters/+page.svelte, src/routes/dashboard/kubernetes/clusters/create/+page.svelte
A couple of enhancements here, first we group resources by project, this then allows us to add a cluster directly into a project rather than having to select from a drop down. The second is that per-project creation also adds in a region dropdown dialog, so that's directly know during creation.  All of this means we can now move all of the dynamic lookup stuff from pages into universal load functions, and do project scoped RBAC rules.
=> Update Cluster Views

charts/ui/Chart.yaml, src/lib/layouts/ErrorPage.svelte, src/routes/+error.svelte, src/routes/error/+page.svelte
This can be redirected to by identity, for example, so it can display branched error messages in the corrct client e.g. during authentication or as a result of user verification work flows.
=> Add an Error Page

charts/ui/Chart.yaml, src/routes/(shell)/+layout.svelte, src/routes/(shell)/compute/clusters/+page.svelte, src/routes/(shell)/identity/groups/+page.svelte, src/routes/(shell)/identity/oauth2providers/+page.svelte, src/routes/(shell)/identity/projects/+page.svelte, src/routes/(shell)/identity/serviceaccounts/+page.svelte, src/routes/(shell)/identity/users/+page.svelte, src/routes/(shell)/kubernetes/clustermanagers/+page.svelte, src/routes/(shell)/kubernetes/clusters/+page.svelte, src/routes/(shell)/regions/identities/+page.svelte, src/routes/(shell)/regions/networks/+page.svelte
There is an apparent race with load functions as part of an async invalidate, and them running as pert of a navigation that causes a bit of a lock up (especially when you have a div blocking everything!). This makes it less likely to occur, but I suspect it can still happen if one's still running when the navigation is triggered.
=> Work Around Race

charts/ui/Chart.yaml, src/routes/(shell)/compute/clusters/+page.svelte, src/routes/(shell)/identity/groups/+page.svelte, src/routes/(shell)/identity/oauth2providers/+page.svelte, src/routes/(shell)/identity/projects/+page.svelte, src/routes/(shell)/identity/serviceaccounts/+page.svelte, src/routes/(shell)/identity/users/+page.svelte, src/routes/(shell)/kubernetes/clustermanagers/+page.svelte, src/routes/(shell)/kubernetes/clusters/+page.svelte, src/routes/(shell)/regions/identities/+page.svelte, src/routes/(shell)/regions/networks/+page.svelte
What feels like a proper fix for the prior commit.  Based on feedback from https://github.com/sveltejs/kit/issues/9354 it appears Svelte gives up if an invalidation happens during a navigation.  Now the user could reclick the button until it works, but it's not intuitive.  Even worse for us, we have a full screen div blocking the UI indicating something is happening!
=> Invalidate Race Workaround

src/lib/forms/MultiSelect.svelte, src/lib/openapi/identity/models/GroupSpec.ts, src/lib/openapi/identity/models/ProjectSpec.ts, src/lib/openapi/identity/models/ServiceAccountCreate.ts, src/lib/openapi/identity/models/ServiceAccountRead.ts, src/lib/openapi/identity/models/ServiceAccountSpec.ts, src/lib/openapi/identity/models/ServiceAccountWrite.ts, src/routes/(shell)/identity/groups/create/+page.svelte, src/routes/(shell)/identity/groups/view/[id]/+page.svelte, src/routes/(shell)/identity/projects/create/+page.svelte, src/routes/(shell)/identity/projects/view/[id]/+page.svelte, src/routes/(shell)/identity/serviceaccounts/create/+page.svelte, src/routes/(shell)/identity/serviceaccounts/view/[id]/+page.svelte, src/routes/(shell)/identity/users/create/+page.svelte, src/routes/(shell)/identity/users/view/[id]/+page.svelte
With really long lists of users and groups and stuff we really want to limit the list sizes, provide a search function and easily be able to see who or what is selected without having to scroll down an entire list.  To the rescue comes Autocomplete.
Fixes #146.
=> Reimagine Multiselects

charts/ui/Chart.yaml, src/lib/layouts/GroupedList.svelte, src/routes/(shell)/compute/clusters/+page.svelte, src/routes/(shell)/kubernetes/clusters/+page.svelte
When there are a great many projects it's best to allow them to be filtered to remove some visula cruft.
Fixes #147.
=> Add Grouped View Filters

src/lib/layouts/ShellListItemMetadata.svelte, src/routes/(shell)/identity/serviceaccounts/+page.svelte, src/routes/(shell)/identity/users/+page.svelte, src/routes/(shell)/regions/networks/+page.svelte
Make it so things are visually the same everywhere e.g. fill in blanks rather than not render anything.  Split multiple metadata options across multiple grid columns to compact the view.
=> Fix Shell List Metadata

charts/ui/Chart.yaml, charts/ui/templates/deployment.yaml, charts/ui/values.yaml, src/lib/clients/index.ts, src/lib/oidc/index.ts, src/routes/(shell)/+layout.ts, src/routes/oauth2/callback/+page.server.ts, src/routes/oauth2/callback/+page.ts, src/routes/oauth2/login/+page.server.ts, src/routes/oauth2/login/+page.ts, src/routes/oauth2/login2/+page.server.ts, src/routes/oauth2/refresh/+page.server.ts, src/routes/oauth2/refresh/+page.svelte
Now the identity service requires a client secret, we need to keep it secret by passing it in as a private environment variable.  This means all authorization functionality needs to be moved server-side rather than exposing it in an SPA.
=> Better OIDC Support

charts/ui/Chart.yaml, charts/ui/templates/deployment.yaml, charts/ui/templates/secret.yaml, charts/ui/values.yaml
And it always comes from a secret so you can control who can see it via Kyverno and friends.  We lose the convenience method of supplying a client name as you need to supply a secret anyway, so may as well grab that at the same time.  You can also override secret creation and supply your own from the External Secrets Operator etc.
=> Allow Client ID/Secret From a Secret

src/routes/(shell)/compute/clusters/+page.svelte, src/routes/(shell)/kubernetes/clusters/+page.svelte
When you first enter the system with an admin account, there will be no projects, so things that expect at least one project will die horribly. Use optional chaining and remove the issue, also preventing users from doing things they cannot do yet.
=> Fix Initial Bringup

src/routes/(shell)/identity/projects/+page.svelte
(...rather than the group icon again)
Fixes #201.
=> Use folder icon for Project items

src/lib/layouts/ShellListItemHeader.svelte, src/routes/(shell)/compute/clusters/+page.svelte, src/routes/(shell)/kubernetes/clusters/+page.svelte, src/routes/(shell)/kubernetes/virtualclusters/+page.svelte
This replaces the account-group icon with the folder-open icon wherever the icon is representing a project rather than an account group.
=> Use folder-open icon for projects

charts/ui/Chart.yaml, src/routes/(shell)/+page.svelte
https://www.skeleton.dev/docs/components/progress-ring/svelte#api-reference suggests that the ProgressRing will calculate the proportion it displays inside the ring, given the `value` and `max`; however, what it _does_ is show the value, with a percentage sign.
To make sure we're showing a percentage, actually calculate it as a percentage and let the `max` default to `100` (and format to `percentage` as before).
=> Show percentage not value in dashboard

src/lib/loadutil.ts, src/routes/(shell)/compute/clusters/create/+page.ts, src/routes/(shell)/kubernetes/clusters/create/+page.ts, src/routes/(shell)/kubernetes/virtualclusters/create/+page.ts
Some things require lists returned from universal load functions to be non-empty, primarily flavors and images.  Add a wrapper promise that raises an error if the assertion fails.
Fixes #213
=> Required Lists in Universal Load Functions

src/lib/layouts/ShellPageHeader.svelte, src/routes/(shell)/compute/clusters/create/+page.svelte, src/routes/(shell)/compute/clusters/edit/[id]/+page.svelte, src/routes/(shell)/compute/clusters/view/[id]/+page.svelte
It's annoying having to click around for things, especially SSH IDs and delete buttons from this point.  Also on creation go straight to the view as it shows status of everything and gives you access to IP addresses which is a much better UX.
=> Improve Compute View

src/lib/logos/Logo.svelte
Using activeElement is wrong as it's used to point to the thing that has focus.  On Chrome/Edge this isn't set, where it is on Firefox.  Using firstChildElement seems to be more appropriate!
=> Fix Logos On Chrome

src/routes/(shell)/compute/clusters/create/+page.ts, src/routes/(shell)/compute/clusters/edit/[id]/+page.ts
This was using the Kubernetes view of these resources, not the compute one!
=> Fix Compute's View of Flavors/Images
