nscaledev/uni-ui

src/lib/ApplicationView.svelte
src/lib/Hint.svelte
src/lib/Item.svelte
src/lib/ItemDetail.svelte
src/lib/Modal.svelte
src/routes/+page.svelte

Fix hovering, and share the global classes more where needed.

Tweak Styles Yet Again

---

src/lib/ClusterCreateModal.svelte
src/lib/ClusterUpdateModal.svelte
src/lib/IconSelectField.svelte
src/lib/LabeledInput.svelte
src/lib/credentials.js
src/routes/+page.svelte

Facilitates communication between the main route and views/modals that require it.

Give Regions a Store

---

package-lock.json
package.json
src/lib/client.ts
src/routes/+layout.svelte
src/routes/applications/catalog/+page.svelte
src/routes/identity/projects/+page.svelte
src/routes/identity/projects/create/+page.svelte
src/routes/infrastructure/clusters/+page.svelte
src/routes/infrastructure/clusters/create/+page.svelte
src/routes/infrastructure/controlplanes/+page.svelte

Push all API errors through a pop-up toast interface.  Also add in the basics of context tracing.

A Toast to the Bride

---

charts/ui/Chart.yaml
src/routes/infrastructure/clusters/create/+page.svelte

The API has been pared back, so remove the unnecessary cruft.

Remove Auto Upgrade

---

charts/ui/Chart.yaml
src/routes/infrastructure/clusters/+page.svelte

Stupid language with its love of undefined rather than "this shit doesn't exist".

Fix Cluster Deletion

---

src/routes/(shell)/+layout.svelte
src/routes/(static)/oauth2/callback/+page.svelte

Add in support for OIDC id_token nonces.

Tighten Authentication

---

src/lib/layouts/ShellPage.svelte
src/lib/openapi/identity/apis/DefaultApi.ts
src/lib/shell/ShellAppBar.svelte
src/routes/(shell)/applications/catalog/+page.svelte
src/routes/(shell)/identity/groups/+page.svelte
src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/groups/view/[id]/+page.svelte
src/routes/(shell)/identity/organizations/+page.svelte

Allow groups to be viewed/updated.

Add More Groups Functionality

---

charts/ui/Chart.yaml
src/lib/shell/ShellAppBar.svelte
src/lib/stores/index.ts

it gets pretty annoying without this!

Remember Organization Choice

---

charts/ui/Chart.yaml
src/lib/clients/index.ts
src/lib/credentials/index.ts
src/lib/login/index.ts
src/lib/oauth2/index.ts
src/lib/oidc/index.ts
src/lib/sessionstore/index.ts
src/lib/shell/ShellAppBar.svelte
src/lib/stores/index.ts
src/routes/(shell)/applications/catalog/+page.svelte
src/routes/(shell)/identity/groups/+page.svelte
src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/groups/view/[id]/+page.svelte
src/routes/(shell)/identity/organizations/+page.svelte
src/routes/(shell)/identity/projects/+page.svelte
src/routes/(shell)/identity/projects/create/+page.svelte
src/routes/(shell)/identity/tokens/+page.svelte
src/routes/(shell)/infrastructure/clustermanagers/+page.svelte
src/routes/(shell)/infrastructure/clusters/+page.svelte
src/routes/(shell)/infrastructure/clusters/create/+page.svelte
src/routes/(static)/oauth2/callback/+page.svelte

Add a bit of creeative sparkle, and also add clipboard support.  Finally use a method to force identity to correctly generate a refresh token, it's not the best, but time constraints etc.

Finish Off PAT Handling

---

src/lib/openapi/identity/apis/DefaultApi.ts
src/lib/openapi/identity/models/Token.ts
src/lib/openapi/identity/models/TokenRequestOptions.ts
src/routes/(shell)/identity/projects/+page.svelte
src/routes/(shell)/identity/projects/view/[id]/+page.svelte

Harnesses the GET and PUT methods for the named project resource.

Enable Project Updates

---

charts/ui/Chart.yaml

Highlights:
* Organization view/update
* AUth2 view/update
* Kubeconfig downloads

Version v0.2.2

---

charts/ui/Chart.yaml
charts/ui/templates/_helpers.tpl
charts/ui/templates/deployment.yaml
charts/ui/templates/ingress.yaml
charts/ui/values.yaml

Pick a select few values and replace with templates that can get their value from a global

Improve Helm

---

src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/oauth2providers/create/+page.svelte
src/routes/(shell)/identity/projects/create/+page.svelte
src/routes/(shell)/infrastructure/clusters/create/+page.svelte

Move to a model where you operate on a full resource, rather than on discrete variables to reduce sprawl, and it makes creation look a lot like updates.  This then leads to a removal of code duplication potentially.

Refactor Resource Creation

---

charts/ui/Chart.yaml
src/lib/layouts/ShellListItem.svelte
src/lib/layouts/ShellListTray.svelte
src/lib/layouts/ShellPage.svelte
src/routes/(shell)/identity/groups/+page.svelte
src/routes/(shell)/identity/oauth2providers/+page.svelte
src/routes/(shell)/identity/projects/+page.svelte
src/routes/(shell)/identity/tokens/+page.svelte
src/routes/(shell)/infrastructure/clustermanagers/+page.svelte
src/routes/(shell)/infrastructure/clusters/+page.svelte

Move list item buttons into a "systray" like component to allow easy modifications across all views.  Also move "create" buttons into a slot in the header to save space and make it look slicker.  Finally add a subtle border to list items to make them pop a bit more.

Tweak Styling

---

charts/ui/Chart.yaml
my-custom-theme.ts
src/lib/WorkloadPoolCreate.svelte
src/lib/formatters/index.ts
src/lib/forms/InputChips.svelte
src/lib/forms/MultiSelect.svelte
src/lib/forms/RangeSlider.svelte
src/lib/forms/Select.svelte
src/lib/forms/SlideToggle.svelte
src/lib/forms/TextInput.svelte
src/lib/layouts/ShellMetadataSection.svelte
src/lib/layouts/ShellSection.svelte
src/lib/validation/index.ts
src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/groups/view/[id]/+page.svelte
src/routes/(shell)/identity/oauth2providers/create/+page.svelte
src/routes/(shell)/identity/organizations/+page.svelte
src/routes/(shell)/identity/projects/create/+page.svelte
src/routes/(shell)/identity/projects/view/[id]/+page.svelte
src/routes/(shell)/infrastructure/clusters/create/+page.svelte
src/routes/(shell)/infrastructure/clusters/view/[id]/+page.svelte

And clean up any other styling woes while we are here.

Add Input Validation

---

charts/ui/Chart.yaml
src/routes/(shell)/identity/groups/+page.svelte

Refers to projects, and it should state the consequences correctly.

Group Delete Dialog Broken

---

charts/ui/Chart.yaml
src/routes/(shell)/identity/groups/+page.svelte
src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/groups/view/[id]/+page.svelte
src/routes/(shell)/identity/oauth2providers/+page.svelte
src/routes/(shell)/identity/oauth2providers/create/+page.svelte
src/routes/(shell)/identity/organizations/+page.svelte
src/routes/(shell)/identity/projects/+page.svelte
src/routes/(shell)/identity/projects/create/+page.svelte
src/routes/(shell)/identity/projects/view/[id]/+page.svelte
src/routes/(shell)/identity/tokens/+page.svelte
src/routes/(shell)/infrastructure/clusters/+page.svelte
src/routes/(shell)/infrastructure/clusters/create/+page.svelte
src/routes/(shell)/infrastructure/clusters/view/[id]/+page.svelte
src/routes/(static)/login/+page.svelte

Improve styling to make it more on brand, reduce reliance on steppers as these are now deprecated.

Stylistic Tweaks

---

charts/ui/Chart.yaml
src/lib/WorkloadPoolCreate.svelte
src/routes/(shell)/infrastructure/clusters/create/+page.svelte

Make things reactive when the the region ID changes, e.g. load up and select new images and flavors.

Fix Multi Region Switching

---

package-lock.json
package.json
src/lib/Flavor.svelte
src/lib/WorkloadPoolCreate.svelte
src/lib/forms/SelectNew.svelte
src/routes/+layout.svelte

Presently when selecting a flavor, we see a list of sausages... Okay not strictly true, we can also see the CPU/RAM/GPU topology too, which brings us to the point of, with all this metadata, do we (or an end user) really care what it's called, as apposed to what it can do?  No is the succinct answer.

Make Flavor Selection "Just Better" (TM)

---

charts/ui/Chart.yaml
src/lib/layouts/BurgerMenu.svelte
src/lib/layouts/BurgerMenuItem.svelte
src/lib/layouts/ShellListItem.svelte
src/lib/layouts/ShellListTray.svelte
src/lib/layouts/ShellSection.svelte
src/lib/shell/ShellAppBar.svelte
src/routes/(shell)/applications/catalog/+page.svelte
src/routes/(shell)/identity/groups/+page.svelte
src/routes/(shell)/identity/oauth2providers/+page.svelte
src/routes/(shell)/identity/projects/+page.svelte
src/routes/(shell)/infrastructure/clustermanagers/+page.svelte
src/routes/(shell)/infrastructure/clusters/+page.svelte
src/routes/(shell)/regions/identities/+page.svelte
src/routes/+layout.svelte

Declutters the main views somewhat and provides a lot more context. Also reduce visual clutter bu simplifying things to be more professional looking.

Add Burger Menus

---

charts/ui/Chart.yaml
src/lib/forms/SelectNew.svelte
src/routes/(shell)/+layout.svelte
src/routes/+layout.svelte
src/routes/+page.svelte

It worked before but not now for some reason, ho hum, add some middleware in to size the new selects correctly.

Fix Popups

---

charts/ui/Chart.yaml
src/routes/(shell)/regions/identities/+page.svelte

Fool of a Took!  Silly typo... note to self, if we can make the endpoints type safe and enumerated somehow using openAPI that would be quite delightful.

Fix Identity RBAC

---

.grype.yaml

... as this removes false positives from the equation.

Add Grype Config

---

src/lib/forms/Button.svelte
src/lib/layouts/ShellList.svelte
src/lib/layouts/ShellListItem.svelte
src/lib/layouts/ShellListItemBadges.svelte
src/lib/layouts/ShellListItemHeader.svelte
src/lib/layouts/ShellListItemMetadata.svelte
src/lib/layouts/ShellListItemSimple.svelte
src/lib/layouts/ShellSection.svelte
src/routes/(shell)/identity/groups/+page.svelte
src/routes/(shell)/identity/oauth2providers/+page.svelte
src/routes/(shell)/identity/projects/+page.svelte
src/routes/(shell)/identity/serviceaccounts/+page.svelte
src/routes/(shell)/identity/users/+page.svelte
src/routes/(shell)/infrastructure/clustermanagers/+page.svelte
src/routes/(shell)/infrastructure/clusters/+page.svelte
src/routes/(shell)/infrastructure/computeclusters/+page.svelte
src/routes/(shell)/regions/identities/+page.svelte
src/routes/(shell)/regions/networks/+page.svelte

Make the base list card generic so it can be used with upto 6 columns and make a couple stylistic tweaks.

Refactor List Cards

---

src/lib/forms/Button.svelte
src/lib/layouts/Stepper.svelte
src/routes/(shell)/infrastructure/clusters/create/+page.svelte
src/routes/(shell)/infrastructure/clusters/view/[id]/+page.svelte
src/routes/(shell)/infrastructure/computeclusters/create/+page.svelte

Or at least remove the dependency on the deprecated stepper implmentation from skeleton which is now deprecated, probably because like me they couldn't find a really nice way of doing it!

Remove Steppers

---

src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/oauth2providers/create/+page.svelte
src/routes/(shell)/identity/projects/create/+page.svelte

Imbue all the create dialogs with a sense of unity.

Normalize Create Button Usage

---

charts/ui/Chart.yaml
src/lib/layouts/ShellMetadataItem.svelte
src/lib/shell/SideBar.svelte

Make Metadata Icons Colorful

---

src/lib/shell/SideBar.svelte

Classic case of too many people asking too many things, leading to distractions and mistakes!

Fix Sidebar Font Weight

---

charts/ui/Chart.yaml
src/lib/KubernetesWorkloadPool.svelte
src/lib/layouts/ResourceList.svelte
src/lib/layouts/ShellList.svelte
src/lib/layouts/ShellListItem.svelte
src/routes/(shell)/infrastructure/clusters/create/+page.svelte
src/routes/(shell)/infrastructure/clusters/view/[id]/+page.svelte
src/routes/(shell)/infrastructure/computeclusters/create/+page.svelte

Fold the controls into the component so they are consitent across everything.  Apply the new paradigm to Kubernetes so it works the same.

Improve Resource Lists

---

src/lib/shell/AppBar.svelte
src/routes/login/+page.svelte

Handle the fallback case when various fields may or may not be present.

Make Profile Handling Better

---

charts/ui/Chart.yaml
package-lock.json

Pulls in a fix for Vite (GHSA-vg6x-rcgg-rjx6).

Upgrade Dev Dependencies

---

src/lib/formatters/index.ts

Stupid language, stupid lack of integers.
Fixes #150.

Fix Age Formatter

---

src/lib/clients/index.ts
src/lib/shell/SideBar.svelte
src/routes/(shell)/compute/clusters/+page.svelte
src/routes/(shell)/compute/clusters/create/+page.svelte
src/routes/(shell)/identity/groups/+page.svelte
src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/groups/view/[id]/+page.svelte
src/routes/(shell)/identity/oauth2providers/+page.svelte
src/routes/(shell)/identity/oauth2providers/create/+page.svelte
src/routes/(shell)/identity/organizations/+page.svelte
src/routes/(shell)/identity/projects/+page.svelte
src/routes/(shell)/identity/projects/create/+page.svelte
src/routes/(shell)/identity/projects/view/[id]/+page.svelte
src/routes/(shell)/identity/quotas/+page.svelte
src/routes/(shell)/identity/serviceaccounts/+page.svelte
src/routes/(shell)/identity/serviceaccounts/create/+page.svelte
src/routes/(shell)/identity/serviceaccounts/view/[id]/+page.svelte
src/routes/(shell)/identity/users/+page.svelte
src/routes/(shell)/identity/users/create/+page.svelte
src/routes/(shell)/identity/users/view/[id]/+page.svelte
src/routes/(shell)/kubernetes/clustermanagers/+page.svelte
src/routes/(shell)/kubernetes/clusters/+page.svelte
src/routes/(shell)/kubernetes/clusters/create/+page.svelte
src/routes/(shell)/kubernetes/clusters/view/[id]/+page.svelte
src/routes/(shell)/regions/identities/+page.svelte

When doing things like creating objects, we probably want to see errors e.g. from quotas being exceeded.
Fixes #149.

Reinstante Toasts

---

src/lib/Flavor.svelte

Handles overflow on mobile devices for things with GPUs primarily.
Fixes #145.

Fix Large Flavors on Mobile

---

src/routes/(shell)/compute/clusters/create/+page.svelte

Fix Compute Creation

---

charts/ui/Chart.yaml
src/routes/(shell)/kubernetes/clusters/create/+page.svelte
src/routes/(shell)/kubernetes/clusters/create/+page.ts

Firts fix a logical bug.  Second, I discovered that error can only be called in a load function, so push the logic into there.

Fix Cluster Creation

---

package-lock.json

Move from RC3 to the GA release.

Skeleton 3 GA

---

charts/ui/Chart.yaml
src/lib/shell/SideBar.svelte

Make the item highlights a little more stylish.

Tweak Nav Styling

---

charts/ui/Chart.yaml
src/routes/(shell)/kubernetes/clusters/create/+page.svelte

THis makes it so the "biggest" lexically is first, which while not a perfect semver comparisson does what you'd expect it to and selects the newest image.

Invert Kubernetes Image Selection Logic

---

charts/ui/Chart.yaml
src/lib/clients/index.ts
src/lib/toaster.ts
src/routes/(shell)/+layout.svelte

Remarkably a lot cleaner than the old code!
Fixes #206

Reinstate Toasts

---

charts/ui/Chart.yaml
src/routes/(shell)/+page.svelte

Because 55.00000000001 displays as that exactly!

Add Rounding to Quota View

---

src/routes/(shell)/compute/clusters/edit/[id]/+page.svelte
src/routes/(shell)/compute/clusters/edit/[id]/+page.ts
src/routes/(shell)/compute/clusters/view/[id]/+page.svelte
src/routes/(shell)/kubernetes/clusters/view/[id]/+page.svelte

Primarily needed to ease testing of the compute service update code that has never really been done before!

Allow Compute Cluster Edits

---

src/routes/(shell)/compute/clusters/+page.svelte
src/routes/(shell)/compute/clusters/view/[id]/+page.svelte
src/routes/(shell)/kubernetes/clusters/+page.svelte

Save space, don't be too descriptive.

Be More Terse With Buttons

---

src/routes/(shell)/+page.svelte

Missed one page when updating the formatting of the header stuff.

Fix Dashboard View

---

src/lib/layouts/ShellListItem.svelte
src/lib/layouts/ShellMetadataSection.svelte
src/lib/layouts/ShellViewHeader.svelte
src/lib/layouts/Stepper.svelte
src/routes/(shell)/identity/groups/create/+page.svelte
src/routes/(shell)/identity/groups/view/[id]/+page.svelte
src/routes/(shell)/identity/oauth2providers/create/+page.svelte
src/routes/(shell)/identity/projects/create/+page.svelte
src/routes/(shell)/identity/projects/view/[id]/+page.svelte
src/routes/(shell)/identity/serviceaccounts/create/+page.svelte
src/routes/(shell)/identity/serviceaccounts/view/[id]/+page.svelte
src/routes/(shell)/identity/users/create/+page.svelte
src/routes/(shell)/identity/users/view/[id]/+page.svelte

Rendering of multiple list items is slightly broken when they differ in height, so force minimum content to fix this.  Improve the design of all pages with better spacing, improve secondary button formatting, allow service accounts to change their metadata.  Finally display the resource ID in the detail views to make use with the API easier.

Fix Some Niggles
